modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CoolAid48/Hands-Off-My-Block/issues"
license = "MIT"

[[mods]]
modId = "handsoffmyblock"
version = "0.2.0"
displayName = "Hands Off My Block"
authors = "CoolAid48"
credits = "Mod icon by PurpleSquirrel1503"
description = '''
Mark workstation blocks and beds to stop villagers from claiming them!
'''

logoFile = "assets/handsoffmyblock/icon.png"

[[mixins]]
config = "handsoffmyblock.mixins.json"
